services:
  - type: web
    name: shreyas-portfolio
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: GMAIL_APP_PASSWORD
        sync: false
